name = "bizwiz3/nova"
version = "0.4.0"
description = "A filesystem-based web framework for Luau runtimes, with out-of-the-box support for Lune and Zune."
authors = ["BizWiz3 (https://github.com/BizWiz3)", "Leoj030 (https://github.com/Leoj030)"]
license = "MIT"
repository = "https://github.com/BizWiz3/nova"
private = false
includes =[
    "pesde.toml",
    "README.md",
    "LICENSE",
    "src/**/*.luau",
    "docs/**/*.md"
]

[target]
environment = "lune"
lib = "src/index.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]

