name = "bizwiz3/nova_ci"
version = "0.1.0"
description = "A high-performance, filesystem-based web framework built specifically for the Lune runtime."
authors = ["BizWiz3 (https://github.com/BizWiz3)", "Leoj030 (https://github.com/Leoj030)"]
license = "MIT"
repository = "https://github.com/BizWiz3/nova"
private = false

[target]
environment = "lune"
bin = "src/index.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
lunemon = { name = "bizwiz3/lunemon", version = "^0.1.1" }
aura = { name = "bizwiz3/aura", version = "^0.1.0" }
