name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lune-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Lune
        run: |
          curl -f -L "https://github.com/lune-org/lune/releases/download/v0.10.4/lune-0.10.4-linux-x86_64.zip" -o lune.zip
          unzip -j lune.zip
          chmod +x lune
          sudo mv lune /usr/local/bin/lune
          rm lune.zip

      - name: Run Lune CI
        working-directory: ./ci
        run: lune run test
  
  zune-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Zune
        run: |
          curl -f -L "https://github.com/Scythe-Technology/zune/releases/download/v0.5.5/zune-0.5.5-linux-x86_64.zip" -o zune.zip
          unzip -j zune.zip
          chmod +x zune
          sudo mv zune /usr/local/bin/zune
          rm zune.zip

      - name: Run Zune CI
        working-directory: ./ci
        run: zune run test