name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  http-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install LPM
        run: |
          curl -f -L "https://github.com/luaupm/lpm/releases/download/v0.5.2/lpm-linux-x86_64.zip" -o lpm.zip
          unzip -j lpm.zip
          chmod +x lpm
          sudo mv lpm /usr/local/bin/lpm
          rm lpm.zip

      - name: Install Dependencies
        run: |
          lpm self install
          lpm i

      - name: Run Test
        working-directory: .
        run: lpm test
