name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t nova-app .

      - name: Run CI Tests
        run: docker run --rm -v ${{ github.workspace }}/ci:/ci -w /ci nova-app lune run test