name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: notes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BODY=$(gh api \
            "repos/${{ github.repository }}/releases/generate-notes" \
            -f tag_name="${{ github.ref_name }}" \
            --jq '.body')

          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.notes.outputs.body }}
          make_latest: true

      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "@everyone A new update has been published!"
          title: ""
          notitle: true
          description: |
            ## [🌖 ${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }})

            ${{ steps.notes.outputs.body }}

          nodetail: true
          color: 0xEBE9EB
          username: Mayari Release
          avatar_url: https://raw.githubusercontent.com/mayari-org/mayari/main/docs/public/mayari.png

  publish-pkg:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: ./.github/actions/install-lpm
      - run: lpm --version

      - name: Restore LPM credentials
        run: |
          mkdir -p ~/.lpm
          echo "${{ secrets.LPM_CREDENTIALS_B64 }}" | base64 -d > ~/.lpm/credentials.toml
          chmod 600 ~/.lpm/credentials.toml

      - name: Publish
        run: lpm publish